### ISSUE TITLE
Limit Autocomplete of TEI Pointers to current document

### ISSUE THREAD

**Issue by NickLaiacona** [performant-software/faircopy#520]
Instead of displaying the XML IDs for every document in the project, the attribute fields for attributes of the type TEI Data Pointer now just display the XML IDs found within the current TEI Document. If the resource isn't in a TEI Document, they should just display the XML IDs found in the current resource.

**Comment by SteveMarvin** [comment]
I can't create new attributes, so this is difficult to test.

**Comment by SteveMarvin** [comment]
Maybe I've misunderstood the issue, or I applied the wrong attribute, but...

OK, so I assigned an XML ID (#lookforthis) to an element in Verbatim Plaintext and then went to FHL_007548733_TAOS_BAPTISMS_BATCH_1_TRANSLATION, and added a CopyOf attribute to another element there. WHen I clicked the field, I saw the #lookforthis ID in the lookup. That was in a different document within the same project. Should I be seeing that? I thought this issue was to limit autocomplete to the current doc...

![image](https://github.com/performant-software/faircopy/assets/18423533/59858da7-9083-46c1-ae81-be94bd5168de)

**Comment by NickLaiacona** [comment]
So two resources may be part of the same TEI Document - in this case FHL_007548733_TAOS_BAPTISMS_BATCH_1_TRANSLATION and Verbatim Plaintext are indeed in the same TEI Document. 

The point of the feature is to limit it to things within the same TEI Document to make it easier to find facsimile surfaces, standoff records, etc that are part of this doc.

**Comment by SteveMarvin** [comment]
OK, I misunderstood. Thanks!
